layout_spectrum: 0.5704291
typography_spectrum: 0.3339552
color:
  saturation: 0.463153
  lightness: 0.5060635
  brandStrength: 0.545709
  rhythmicContrast: 1
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: 1st time home buyers
